### ISSUE TITLE
Error when using a zipped CSV and have multiple splits.

### ISSUE THREAD

**Issue by mohitmathew** [mvallebr/CSVInputFormat#10]
I got the below error when processing a zipped csv file and forcing multiple splits by giving small LINES_PER_MAP .
This below error comes for the last chunk.

java.lang.Exception: java.io.EOFException: Cannot seek after EOF
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:406)
Caused by: java.io.EOFException: Cannot seek after EOF
    at org.apache.hadoop.hdfs.DFSInputStream.seek(DFSInputStream.java:1459)
    at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:62)
    at com.pointcross.CSVLineRecordReader.initialize(CSVLineRecordReader.java:213)
    at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:478)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:671)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:330)
    at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:268)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

**Comment by mvallebr** [comment]
Sorry for the delay @mohitmathew , It sounds like the zip file is really corrupted... Are you sure it's not the case? 
Would you be able to submit a test file where the problem happens? It would make it easier to provide a fix
